name: SonarCloud

on: [push]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v1.8
        with:
          organization: nicklasjepsen
          token: ${{ secrets.SONAR_TOKEN }}
